apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
data:
  password: a2FyYW5AMTIz
---
apiVersion: v1
kind: Service
metadata:
  name: docker-mysql
  labels:
    app: docker-ci
spec:
  ports:
    - port: 3306
  selector:
    app: docker-ci
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: docker-ci
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mysql
  labels:
    app: docker-ci
spec:
  selector:
    matchLabels:
      app: docker-ci
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: docker-ci
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: todos
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim