apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-ci-app
  labels:
    app: docker-ci
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-ci
      tier: frontend
  template:
    metadata:
      labels:
        app: docker-ci
        tier: frontend
    spec:
      containers:
      - name: docker-ci
        image: karanpatel12/getting-started:v1
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_HOST
          value: docker-mysql
        - name: MYSQL_DB
          value: todos
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        volumeMounts:
        - name: docker-persistent-storage
          mountPath: /etc/todos
      volumes:
      - name: docker-persistent-storage
        persistentVolumeClaim:
          claimName: docker-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: docker-ci-frontend
  labels:
    app: docker-ci
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: docker-ci
    tier: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000